EXPERIMENT:
  NAME: "wrn_40_2_wrn_16_2"
  TAG: "wrn_40_2_wrn_16_2"
  PROJECT: "wrn_40_2_wrn_16_2"
DISTILLER:
  TYPE: "CAT_KD"
  TEACHER: "wrn_40_2"
  STUDENT: "wrn_16_2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

CAT_KD:
  LOSS:
    # Î²
    CAT_loss_weight: 12.
    # the resolution of the transferred CAMs after the average pooling function
    CAM_RESOLUTION: 2
    CE_WEIGHT: 1.
  #True: CAT
  #False: CAT-KD
  onlyCAT: False
  IF_NORMALIZE: False

# true: convert the normal CNN to our style
if_test: True
device: 0