EXPERIMENT:
  NAME: "imagenet_r34_r18"
  TAG: "imagenet_r34_r18"
  PROJECT: "imagenet_r34_r18"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "CAT-KD"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 2
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"

CAT_KD:
  LOSS:
    # Î²
    CAT_loss_weight: 0.5
    # the resolution of the transferred CAMs after the average pooling function
    CAM_RESOLUTION: 4
    CE_WEIGHT: 1.
  #True: CAT
  #False: CAT-KD
  onlyCAT: False
  IF_NORMALIZE: False

# true: convert the normal CNN to our style
if_test: True
device: 0

LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
  WANDB: False
